ALTER TABLE towers
ADD COLUMN IF NOT EXISTS vendor TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS snmp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS snmp_version TEXT NOT NULL DEFAULT 'v2c',
ADD COLUMN IF NOT EXISTS snmp_target TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS snmp_community TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS snmp_v3_user TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS snmp_auth_protocol TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS snmp_auth_password TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS snmp_priv_protocol TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS snmp_priv_password TEXT NOT NULL DEFAULT '';
